# Generated by Django 5.2.8 on 2025-11-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('smartphones', 'smartphones'), ('notebooks', 'notebooks'), ('smart TVs', 'smart TVs')], max_length=20)),
                ('tensao', models.IntegerField()),
                ('dimencoes', models.CharField(max_length=20)),
                ('resolucao', models.CharField(max_length=20)),
                ('capacidade', models.IntegerField()),
                ('conectividade', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provaSaep.estoque')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provaSaep.usuario')),
            ],
        ),
    ]
